version: "3.7"

services:
  sanitized-service-name:
    image: 172.32.5.240:5050/sanitized-service-name:currentBuild.number
    ports:
      - "8090:8090"
    networks:
      - sanitized-networkname1
      - sanitized-networkname2
      
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure

    environment:
      - PORT=8090

networks:
  sanitized-networkname1:
    external: true
  sanitized-networkname2:
    external: true

