pipeline {

    agent any
    
    environment {
        NEXUS_URL  = '172.32.5.240:5050'
        IMAGE_URL_WITH_TAG = "${NEXUS_URL}/sanitized-servicename:${currentBuild.number}"
    }

    stages {
        
        stage("sonarqube analysis"){
        steps{
         nodejs(nodeJSInstallationName: 'NodeJS16'){
            sh "npm install"
             withSonarQubeEnv("SonarQube") {
                  sh "npm install jest"
                  sh "npm run test"
                  sh "npm install sonar-scanner"
                  sh "npm run sonar"
            }
          }
        }         
      }

        
        stage('Building Docker Image') {
            steps {
                sh "docker build . -t ${IMAGE_URL_WITH_TAG}"
            }
        }

        stage('Push to In-house Nexus Docker Registry') {
            steps {
                withCredentials([string(credentialsId: 'nexus-pwd', variable: 'nexusPwd')]) {
                    sh 'docker login -u sanitized-username -p ${nexusPwd} ${NEXUS_URL}'
                    sh "docker push ${IMAGE_URL_WITH_TAG}"
                }
            }
        }
        
        stage('Send Deployment Artifacts to sanitized-server-name') {
            steps {
                sh 'chmod +x changeTag.sh'
                sh "./changeTag.sh ${currentBuild.number}"
    
                sshPublisher(publishers: [sshPublisherDesc(configName: 'sanitized-server-name', transfers: [sshTransfer(cleanRemote: false, excludes: '', execCommand: '', flatten: false, makeEmptyDirs: false, noDefaultExcludes: false, patternSeparator: '[, ]+', remoteDirectory: '/pipelines/sanitized-servicename/', remoteDirectorySDF: false, removePrefix: '', sourceFiles: '*.yml')], usePromotionTimestamp: false, useWorkspaceInPromotion: false, verbose: false)])
            }
        }


        stage('Deploy service in sanitized-server-name') {
            steps {
               sshPublisher(publishers: [sshPublisherDesc(configName: 'sanitized-server-name', transfers: [sshTransfer(cleanRemote: false, excludes: '', execCommand: 'docker login -u sanitized-username -p sanitized-password 172.32.5.240:5050 && docker stack deploy -c /home/sanitized-user/pipelines/sanitized-servicename/docker-compose.yml sanitized-servicename --with-registry-auth', flatten: false, makeEmptyDirs: false, noDefaultExcludes: false, patternSeparator: '[, ]+', remoteDirectory: '', remoteDirectorySDF: false, removePrefix: '', sourceFiles: '')], usePromotionTimestamp: false, useWorkspaceInPromotion: false, verbose: false)])
            }
        }
    }
}

