version: "3.5"

services:
  lending-api-gateway:
    image: 172.32.5.240:5050/lending-api-gateway:currentBuild.number
    ports:
      - "8888:8888"
    networks:
      - credit-pro-overlay

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure

    environment:
      - APPLICATION_PORT=8888

    #volumes:
     # - /config:/app/config
     # - /policies:/app/policies
     # - /plugins:/app/plugins

networks:
  credit-pro-overlay:
    external: true





